#This is the line of code for Day 1 Project "Band Name Generator" (Beginner Level)
print("Welcome to the Band Name Generator.")
city = input("What's the name of city you grew up in?\n")
pet = input("What's your pet's name?\n")
print("Your band name could be " + city + " " + pet)
